# Generated by Django 4.2.1 on 2023-05-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='rating_comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='rating_post',
        ),
    ]
